"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="h-full bg-white">
      <body className={`${inter.className} h-full`}>
        <SessionProvider >{children}</SessionProvider>
      </body>
    </html>
  );
}
