import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/free-brands-svg-icons";
config.autoAddCss = false;
import ToasterContext from "@/components/ToasterContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

// {/* <div>
//           <button><FontAwesomeIcon icon={faBars} /></button>
//             <ul>
//               <li><Link href="./">Accueil</Link></li>
//               <li><a href='#impressionDesDocuments'>Impression des documents</a></li>
//               <li><a href="#guideDesFormations">Guide Formations</a></li>
//             </ul>
//         </div> */}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full bg-white font-satoshi">
        <Provider ><ToasterContext />{children}</Provider>
      </body>
    </html>
  );
}
